# Generated by Django 4.0.3 on 2022-03-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
        ('ask', '0002_ask_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.year'),
        ),
    ]
