# Generated by Django 4.0.3 on 2022-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualifi', models.CharField(max_length=50)),
                ('Celsius', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(height_field=350, upload_to='Home/slide', width_field=700)),
                ('slide2', models.ImageField(height_field=350, upload_to='Home/slide', width_field=700)),
                ('slide3', models.ImageField(height_field=350, upload_to='Home/slide', width_field=700)),
                ('about', models.CharField(max_length=750)),
                ('Awarded', models.CharField(max_length=50)),
                ('Awarded2', models.CharField(max_length=50)),
                ('coun', models.IntegerField()),
                ('coun2', models.IntegerField()),
                ('coun3', models.IntegerField()),
                ('coun4', models.IntegerField()),
                ('degree', models.ManyToManyField(to='dashboard.degree')),
            ],
        ),
    ]
