# Generated by Django 4.0.3 on 2022-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='Celsius',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='degree',
            name='Qualifi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='Awarded',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='Awarded2',
            field=models.CharField(max_length=100),
        ),
    ]
