# Generated by Django 4.0.3 on 2022-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_home_slide_alter_home_slide2_alter_home_slide3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slide',
            field=models.ImageField(upload_to='Home/slide'),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide2',
            field=models.ImageField(upload_to='Home/slide'),
        ),
        migrations.AlterField(
            model_name='home',
            name='slide3',
            field=models.ImageField(upload_to='Home/slide'),
        ),
    ]
