# Generated by Django 4.0.3 on 2022-03-12 15:09

import blog.utlis
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=blog.utlis.cover_directory_path)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
