# Generated by Django 4.0.3 on 2022-03-27 11:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', tinymce.models.HTMLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doctor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.year')),
            ],
        ),
    ]
