# Generated by Django 4.0.3 on 2022-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_year_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
