# Generated by Django 4.0.3 on 2022-03-28 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_lecture_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='body',
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='Lecture', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
