# Generated by Django 4.0.3 on 2022-03-30 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_remove_lecture_body_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Lecture', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
